apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ant-publisher
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ant-publisher
    spec:
      containers:
      - name: ant-publisher
        image: tikal/ants-publisher:{{.Values.image.tag}}"
        ports:
         - containerPort: 6080
        volumeMounts:
        - name: conf
          mountPath: {{ .Values.confMountDir }}
      volumes:
      - name: conf
        configMap:
          name: ant-publisher-conf
---
apiVersion: v1
kind: Service
metadata:
  name: ant-publisher
spec:
 selector:
  app: ant-publisher
 ports:
  - name: "input"
    port: 6080
    targetPort: 6080   
 type: LoadBalancer

       

          

 
