apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name:
    ? include "ant-publisher.fullname" .: null
    : null
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app:
          ? include "ant-publisher.name" .: null
          : null
    spec:
      containers:
        name:
          ? include "ant-publisher.name" .: null
          : null
        image: tikal/ant-publisher:1.1.98
        ports:
          containerPort: 6080
        volumeMounts:
          name: conf
          mountPath:
            ? .Values.confMountDir: null
            : null
      volumes:
        name: conf
        configMap:
          name: ant-publisher-conf.json
