apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "ant-ui.name" . }}
  labels:
    app: {{ template "ant-ui.name" . }}
    chart: {{ template "ant-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: "{{ .Values.replicaCount }}"
  template:
    metadata:
      labels:
        app: {{ template "ant-ui.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        name: {{ template "ant-ui.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
