image:
  repository: tikal/ants-publisher
  tag: tikal/ant-publisher:1.1.128
  pullPolicy: Always
service:
  port: 6080
  type: LoadBalancer
confMountDir: /opt/firehose/conf
serviceName: ac-kafka
namespace: ant-publisher
