apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ants-firehose
  namespace: ant-crash
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ants-firehose
    spec:
      containers:
      - name: ants-firehose
        image: tikal/ants-firehose
        ports:
         - containerPort: 7080
        volumeMounts:
        - name: conf
          mountPath: /opt/firehose/conf
      volumes:
      - name: conf
        configMap:
            name: ant-firehose-conf
---
apiVersion: v1
kind: Service
metadata:
  name: ants-firehose
  namespace: ant-crash
spec:
 selector:
  app: ants-firehose
 ports:
  - name: "input"
    port: 7080
    targetPort: 7080   
 type: LoadBalancer

       

          

 
