apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "ants-firehose.name" . }}
spec:
  replicas: "{{ .Values.replicaCount }}"
  template:
    metadata:
      labels:
        app: {{ template "ants-firehose.name" . }}
    spec:
      containers:
        name: {{ template "ants-firehose.name" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
          containerPort: {{ .Values.service.port }}
        volumeMounts:
          name: conf
          mountPath: {{ .Values.confMountDir }}
      volumes:
        name: conf
        configMap:
          name: ant-firehose-conf
