apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: '{{ include "ants-firehose.name" . }}'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: '{{ include "ants-firehose.name" . }}'
    spec:
      containers:
        name: '{{ include "ants-firehose.name" . }}'
        imagePullPolicy: '{{ .Values.image.pullPolicy }}'
        image: tikal/ant-firehose:1.0.80
        ports:
          containerPort: 7080
        volumeMounts:
          name: conf
          mountPath: '{{ .Values.confMountDir }}'
      volumes:
        name: conf
        configMap:
          name: ant-firehose-conf
