apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name:
    ? include "ants-firehose.name" .: null
    : null
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app:
          ? include "ants-firehose.name" .: null
          : null
    spec:
      containers:
        name:
          ? include "ants-firehose.name" .: null
          : null
        imagePullPolicy:
          ? .Values.image.pullPolicy: null
          : null
        image: tikal/ant-firehose:1.0.82
        ports:
          containerPort: 7080
        volumeMounts:
          name: conf
          mountPath:
            ? .Values.confMountDir: null
            : null
      volumes:
        name: conf
        configMap:
          name: ant-firehose-conf
