---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ants-firehose
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ants-firehose
    spec:
      containers:
      - name: ants-firehose
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: {{ .Values.image.repository }}
        ports:
        - containerPort: 7080
        volumeMounts:
        - name: conf
          mountPath: {{ .Values.confMountDir }}
      volumes:
      - name: conf
        configMap:
          name: ant-firehose-conf

