apiVersion: v1
kind: Service
metadata:
  name: {{ template "ant-firehose.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "ant-firehose.name" . }}
    helm.sh/chart: {{ template "ant-firehose.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/name: {{ template "ant-firehose.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: "input"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}