replicaCount: 1
image:
  repository: tikal/ants-ui
  tag: tikal/ant-ui:1.0.248
  pullPolicy: Always
service:
  type: LoadBalancer
  port: 80
  targetPort: 5000
ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
  - chart-example.local
  tls: []
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
namespace: ant-ui
