apiVersion: v1
kind: Service
metadata:
  name: ants-firehose
  labels:
    app: {{ template "ants-firehose.name" . }}
    chart: {{ template "ants-firehose.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: ants-firehose
  ports:
    - name: "input"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}